name: Python API Server Tests

on:
  push:
    branches: [main]
    paths:
      - 'api-server/**'
  pull_request:
    branches: [main]
    paths:
      - 'api-server/**'

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        uses: astral-sh/setup-uv@v2
        with:
          cache: true

      - name: Install dev dependencies with uv
        working-directory: api-server
        run: |
          uv sync --group dev

      - name: Set JWT secret for tests
        run: echo "JWT_SECRET_KEY=test_secret" >> $GITHUB_ENV

      - name: Run tests with pytest and coverage
        working-directory: api-server
        run: |
          uv run pytest --cov=app --cov-report=xml --cov-report=term-missing -v --junitxml=pytest-report.xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: exospherehost/exospherehost
          files: api-server/coverage.xml
          flags: unittests
          name: codecov-coverage-report
          fail_ci_if_error: true
